#!/usr/bin/env bash
# Regenerate NuGet.config.
#
# The engine's bundled Godot.NET.Sdk lives inside the nix store, and that path
# carries a content hash that changes on every nixpkgs update. Hardcoding it
# means the build breaks the next time the system is rebuilt with the error
#   MSB4236: The SDK 'Godot.NET.Sdk/4.7.1' specified could not be found
# so the path is derived from whichever godot-mono is currently on PATH.
set -euo pipefail

cd "$(dirname "$0")/.."

bin="$(command -v godot-mono || command -v godot4-mono || true)"
if [ -z "$bin" ]; then
  echo "godot-mono not found on PATH" >&2
  exit 1
fi

# .../libexec/.godot...-wrapped  ->  .../share/nuget/packages
root="$(dirname "$(dirname "$(readlink -f "$bin")")")"
pkgs="$root/share/nuget/packages"

if [ ! -d "$pkgs" ]; then
  # The wrapper derivation re-exports the real package; follow one more hop.
  pkgs="$(dirname "$(dirname "$root")")/share/nuget/packages"
fi
if [ ! -d "$pkgs" ]; then
  pkgs="$(ls -d /nix/store/*godot-mono-*/share/nuget/packages 2>/dev/null | head -1)"
fi
if [ ! -d "$pkgs" ]; then
  echo "could not locate the engine's bundled nuget packages" >&2
  exit 1
fi

cat > NuGet.config <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tools/setup-nuget.sh. Re-run after any nixpkgs update. -->
<configuration>
  <packageSources>
    <clear />
  </packageSources>
  <fallbackPackageFolders>
    <clear />
    <add key="godot-nix" value="$pkgs" />
  </fallbackPackageFolders>
</configuration>
EOF

echo "NuGet.config -> $pkgs"
